### ISSUE TITLE
CommonJS 'index' doesn't appear to be getting published

### ISSUE THREAD

**Issue by tom-youd** [marijnh/find-cluster-break#1]
Trying to consume this package as CommonJS via `@codemirror/state` I am getting this error
```
Cannot find module '@marijn/find-cluster-break' from 'node_modules/@codemirror/state/dist/index.cjs'
```

When I look at the `dist` folder for this package all I see is a types file.
![Screenshot 2024-12-09 at 16 10 41](https://github.com/user-attachments/assets/911f5c20-af1b-4f86-9723-0f34f74d8b92)

I'm assuming that's because npm publish is falling back to the `.gitignore` file and removing it
https://github.com/marijnh/find-cluster-break/blob/main/.gitignore#L3

**Comment by marijnh** [comment]
Oh right, npm defaults to using `.gitignore` when there's no `.npmignore` file. I've added such a file to sidestep the issue.
